[package]
name = "criterion_truncation_bug"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "benchmark"
harness = false
